### ISSUE TITLE
When will the paper be released?

### ISSUE THREAD

**Issue by freshwk** [JinyuanLiu-CV/TarDAL#1]
Congradulations!  I want to know when will the paper be released?

**Comment by guihuiL** [comment]
I also want to ask the same question. Thanks for your contribution!

**Comment by Rolling-Plain** [comment]
@freshwk @GHGluck 
Thank you for your attention to our work! At present, we have submitted the paper to ArXiv and disclosed the download ways of our dataset. You can browse the homepage to get them. Thank you again and good luck!
