### ISSUE TITLE
请问论文中的yolov5是如何训练的呢？

### ISSUE THREAD

**Issue by linklist2** [JinyuanLiu-CV/TarDAL#12]
在论文中，提到使用yolov5去进行目标检测然后对比不同的融合算法的效果。

> To thoroughly discuss how does IVIF influences multi- modality object detection performance, two datasets, i.e., Multispectral and M3FD, are employed. In which, we utilized YOLOv5 as the baseline model for object detection. For fair comparison, we retain the detection model on the fused result of seven state-of-the-art methods, respectively

请问这里的yolov5是如何训练的呢？

是将不同融合算法得到的融合图像作为训练集送入到yolov5当中吗？然后去验证同一个验证集里的检测效果吗？

**Comment by misakicoca** [comment]
YOLO训练相关问题 @Rolling-Plain

**Comment by Rolling-Plain** [comment]
以TarDAL为例：将TarDAL得到的融合图像划分为训练集与验证集，送入训练集到yolov5中重新训练，并在验证集上评价检测效果。
在横向对比中，所有方法的训练集与验证集划分一致

> 在论文中，提到使用yolov5去进行目标检测然后对比不同的融合算法的效果。
> 
> > To thoroughly discuss how does IVIF influences multi- modality object detection performance, two datasets, i.e., Multispectral and M3FD, are employed. In which, we utilized YOLOv5 as the baseline model for object detection. For fair comparison, we retain the detection model on the fused result of seven state-of-the-art methods, respectively
> 
> 请问这里的yolov5是如何训练的呢？
> 
> 是将不同融合算法得到的融合图像作为训练集送入到yolov5当中吗？然后去验证同一个验证集里的检测效果吗？
