### ISSUE TITLE
您好，我想进一步了解一下您的数据集是如何实现配准的。

### ISSUE THREAD

**Issue by chenhaitao405** [JinyuanLiu-CV/TarDAL#7]
”We first calibrated all cameras to estimate their internal and external parameters, and then calculated a homography matrix that projects coordinates of infrared images to those of the visible. “
您的文章中提到，您是通过标定相机的内外参来估计单应性矩阵的，我理解中不同距离下拍摄的图像使用的单应性矩阵应该是不能通用的，您是如何通过内外参来估计单应性矩阵的？

**Comment by MisakiCoca** [comment]
您好，非常感谢您对我们工作的关注！
已将您的问题分配给 @Rolling-Plain 解答。

**Comment by Rolling-Plain** [comment]
> ”We first calibrated all cameras to estimate their internal and external parameters, and then calculated a homography matrix that projects coordinates of infrared images to those of the visible. “ 您的文章中提到，您是通过标定相机的内外参来估计单应性矩阵的，我理解中不同距离下拍摄的图像使用的单应性矩阵应该是不能通用的，您是如何通过内外参来估计单应性矩阵的？

您好，我们在标定相机时考虑到距离因素，在不同的距离条件下均进行了单应性矩阵的估算，并最终选取了较为折中的距离处对应配准性能较好的单应性矩阵。在实际拍摄后，我们根据图片中环境所示相机距离通过人工观察和手动微调单应性矩阵完成最终的配准。

**Comment by MisakiCoca** [comment]
若您仍对该问题存在疑惑，可以在此继续提问，我们会在第一时间内为您解答。
没有更新的情况下，一天后我们将关闭此 commit 。 @chenhaitao405

**Comment by chenhaitao405** [comment]
好的，明白了，非常感谢您的快速回复
