### ISSUE TITLE
有关掩膜数据的提取方式

### ISSUE THREAD

**Issue by ejajaja** [JinyuanLiu-CV/TarDAL#8]
Hello. Thank you for your great work. But may I know where can I get the mask data as in mk in fusion_data.py?

**Comment by MisakiCoca** [comment]
您好，非常感谢您对我们工作的关注！
通常而言，在当前版本中，我们并未将「掩膜提取」功能作为代码的一部分。
您可以使用您偏好的算法对红外图像进行掩膜提取，如 

- `有监督算法：U-2-Net`
- `无监督算法：Deepusps`
- `传统算法：opencv.StaticSaliencyFineGrained`

在 `CVPR Rebuttal` 阶段，我们已经证实，使用上述提到的不同的掩膜提取方式不会使融合结果存在巨大差异。

在近期，我们将发布新版本的代码，将内置「掩膜提取」「IQA计算」等预处理步骤以方便其余研究人员重新部署 `TarDAL`。

若您仍对该问题存在疑惑，可以在此继续提问，我们会在第一时间内为您解答。
没有更新的情况下，一天后我们将关闭此 commit 。

**Comment by ejajaja** [comment]
thank you for responding. 
I have another question. 
What is vsm data?

**Comment by MisakiCoca** [comment]
代码中所提到的 `VSM` 为 `Visual Saliency Map`，是我们 `IQA` 的方式。
同样，当前版本中并未内置该部分预处理步骤，该功能将在新版本代码中内置。

> 在近期，我们将发布新版本的代码，将内置「掩膜提取」「IQA计算」等预处理步骤以方便其余研究人员重新部署 `TarDAL`。

目前，您可以使用如下方式进行计算：

- 神经网络：如同 `U2Fusion` 一样，使用 `VGG` 网络的部分层输出加权归一
- 传统算法【论文使用】：使用 `LC` 算法 - 基于全局对比度图像显著性检测

希望我的回答对您所有帮助，预祝您实验顺利。
